# Generated by Django 5.0.6 on 2024-06-03 04:06

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
    #    ("migrations", "0001_initial")
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empcode', models.TextField(db_column='EMPCODE', max_length=4)),
                ('username', models.CharField(db_column='USER NAME', max_length=255)),
                ('department', models.CharField(db_column='DEPT NAME', max_length=255)),
                ('designation', models.CharField(db_column='DESIGNATION', max_length=255)),
                ('qualification', models.CharField(db_column='HIGHESTQUALIFICATION', max_length=255)),
                ('email', models.CharField(db_column='EMAIL', max_length=255)),
                ('extension', models.CharField(db_column='EXTENSION', max_length=255)),
                ('mobile', models.CharField(db_column='MOBILE', max_length=10)),
                ('gender', models.TextField(max_length=10,db_column='SEX')),
                ('dob', models.DateField(max_length=10,db_column='DOB')),
                ('img_brief', models.ImageField(upload_to='static/img',db_column='IMG'))
            ],
            
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empcode', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        
    ]
