# Generated by Django 4.2.13 on 2024-06-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(db_column='DEPT NAME', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(db_column='DESIGNATION', max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(blank=True, db_column='DOB', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(db_column='EMAIL', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='extension',
            field=models.CharField(db_column='EXTENSION', max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(db_column='MOBILE', max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='qualification',
            field=models.CharField(db_column='HIGHESTQUALIFICATION', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(db_column='USER NAME', max_length=100),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='userlogin',
        ),
    ]
